name: CI
on:
  push:
    branches: [ "main" ]
permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: extractions/setup-just@v1
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: test
        run: just test
